language: java

os: linux

jdk:
  - oraclejdk8

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y gcc-multilib

install:
  - make runtime
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - MAVEN_OPTS="-Xss8m" | mvn test -B
